name: Build

on:
  push:
    branches:
      - develop*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Europe/London

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential flex bison dwarves libssl-dev libelf-dev bc \
            tzdata python3

      - name: Configure kernel
        run: |
          cp Microsoft/config-wsl .config
          ./scripts/config --enable CONFIG_BT
          ./scripts/config --enable CONFIG_BT_HCIBTUSB
          ./scripts/config --enable CONFIG_RFKILL
          echo "-wslbt" > localversion
          make olddefconfig

      - name: Build kernel and modules
        run: |
          make -j$(nproc)
          make modules -j$(nproc)
          make modules_install INSTALL_MOD_PATH=output/modules
          mkdir -p output
          cp arch/x86/boot/bzImage output/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts2
          path: output/**
